version: '3.8'

services:
  backend:
      build:
        context: ./lab1_back
        dockerfile: Dockerfile
      volumes:
        - backend_data:/app/lab1_back
      ports:
        - "5000:5000"
      restart: always

  frontend:
    ports:
        - "80:80"
    build:
      context: ./lab1_front
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend

volumes:
  frontend_data:
  backend_data:

networks:
  default:
    driver: bridge